#!/bin/bash
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

plugin=libopenjdkjvmtid.so
agent=libtiagentd.so
lib=tiagentd
if  [[ "$@" == *"-O"* ]]; then
  agent=libtiagent.so
  plugin=libopenjdkjvmti.so
  lib=tiagent
fi

if [[ "$@" == *"--jvm"* ]]; then
  arg="jvm"
else
  arg="art"
fi

if [[ "$@" != *"--debuggable"* ]]; then
  other_args=" -Xcompiler-option --debuggable "
else
  other_args=""
fi

./default-run "$@" --experimental agents \
                   --experimental runtime-plugins \
                   --runtime-option -agentpath:${agent}=905-object-free,${arg} \
                   --android-runtime-option -Xplugin:${plugin} \
                   ${other_args} \
                   --args ${lib}
